language: bash
services: docker
before_script:
- echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
- sudo service docker restart
script:
- docker build --squash -t mydatakeeper/archlinux .
deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    && docker push mydatakeeper/archlinux
  on:
    branch: master
env:
  global:
  - secure: EqwelmRX6LX5sqXONCQpf1/bas5dkOyl9YnAHJsL/grk3EbMVe5eSIYVvHN56yLcwGX9OxhKEXPuk9p1ybxxWgUTPoBylTra6vFk/0MKBTEFFMw7UzHH64KtkRExVOS+Y/Nfr47IVggG8GdItXOnuOHCKnRONQJrLvoBTK9W3zkbn5JwJKX62+GgKaFdiITipJsQQevj5zTzL5L4O218z7045ryadQ6m/pyqkepnmk7LrUWysgv/LAJXjXDGku8ydPZTF2QqZkakH3XRz5oftkoCRVe+SIFl8v3TKOHOyLRZLN6/PVD4hizvAPCbnLslulQ7sy4NGb8CuX6qfVmqJ85oxykWMW2x5GRnth0E1oaWiHZp2CzDBI35RmJslZoz8zgiUu+D8ejD0db9se1KmqB/pKOF5g6XwbzN+EMWoHnbP2mAbVFPl/O94q0QAtb1b/pVwDwT8l+qc528mgoyA7W1KINcfU2TgWfI0PqSGhKOTK1ndVKrx+Cq1A5+3HAKMOyrrBOZd+MXsL632cD+TbmW496okF20vAehZk3MXyrzEgdfdZ+o38CXdsXoH5DK0kNNNyxC2SRaFweMdVUIlkoOPVbZDpz72pW/VTpy7bJwIq5rZD5Pc5sFeNpEG4aRkiQcRCBMjInnIer+bl/5pnTg3acxG5EGrC4QDUc5NuQ=
  - secure: ebITAeeB3vLdwhtU6jN6/vW1ujXE4nQkHQT7w40vWAkkApdvmpcoZZCaOT18KeHlOdsKSyjRr73QvqsJnR4d74/BSeaVGlgIrxNmQYNkXg4h+V49D/oVXUNVrCfiLxTqMUhK5AzTzMIcqcwOitFseKbfJdhfTHlGsiAX8CvuFtyIu+FjvnjWQEw9Odul+EpHM81kspCpElwFPEosecal1cpz+Mb/HQZwerteAoMObNxRw620nf2TgWB2g4y0Sx2wzz+lEOM3XW4NstpW/G9FQubBJGj7jpc9OaqLOaSOOLuyZTa118q4Mv61A9rk9nvx3T8wLAPhpXbF+/ScFxp/M89C7OV8s9B7aw0uly7JVlmFK5zgCYrNOVmaDENKovavwKGUm9ksHRfj9wPkCsoAlwiU+Cvzmf4YlDdigvZ2cAxK6F+YTppLNCfZ/CmSxoNmTcY9FdhDLX39tIbpAgYuWSqjkMhANbQzsNRZWJf7lxFiv3vPs6IIJ8r7doGm2pvaBPNwYNav2Sb/4GlEs4SHp/uJg7iIPfr/KfwHqz+n06UeAVGpd1Cu2cIaL/fYNu7+X5Z4rzxhqJ4wb9iPA5pXENom8ErynN2FEIeToQRBtuAPNfI7txP9xopeor56+/Dz4uTjJGnqvpl+1flzGN54nrbuy9K3A6BmSzbGpk4bhO0=
