language: bash
services: docker
before_script:
- echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
- sudo service docker restart
script:
- docker build --squash -t mydatakeeper/archlinux .
deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    && docker push mydatakeeper/archlinux
  on:
    branch: master
env:
  global:
  - secure: JSIPlXp/WGnxA6JK9EQAomLIMrYTssV7+ZF8uQbbw5+HHjfHDSgBZIUVfgJTDRQD/GJF4N/SPIhmJsCYsVhA3yZ6bMjMZarZREkIGXSGzdBzjM34A5J1z7X8imGwqX22EIQTOrCYeCNstYfu0wS5Dl+UCe5setEv2uFrodPmdryCopKXurBNMuQ/NTKAPnHzf5EKkOD81aTwJ2S81JQybHPWhVe0XxjyxOEK8sNLHKf+2qMf0WvhEiQhOEVMiMo4+qIWu8ocvnboi5VRKPv/u8wj2ImsUNJDPVHdLMps5/DwKgPcxSQh4EMdnaf7mysW4Zz/GpZfdRXTNcYEqLVQFWfGEoy0BFt3YQOryZy+apERXp7SX3fGEbPncQqjvW2qp5ueTYlr2qRSF7FyzgtYqumUBA611fUaeAFUB3P7GziNZGZoVkPPkLfLTU5c/u9doDJYQdU3WK81HXGLQ+m2FPt8wXq09Nf/6+c7tT1UuEGVpOj8b5pYl+1Q5CITy+WzCr1izZVFLmQFkD5JYfqTuyuI3g9HtO7SZ9STm7OslUE0Q5rVSZhcoqnkOPn/MZjc3LsL2JR9qlA9axlff19Xm6A6YsksP36bONuqYB2BeZRh+lXtWJ36iE0lFhWhZrvM4126zxnMyKr7jTqWSmfsX2SEK1n+3rpI5eSkMHR0iMg=
  - secure: aKtxj/KBpDx+066xKdsrBjm1Q31L1VzgytJoujeMiHxrwhgJ0XVeMvIJPpT6CZxHkT9pxxr/lFzoR2H7KwqLb3j8BYmHyNeLPshJ9wQvHZfV1H2Jrag+k3yfcQUAV1ERFqZS9LC9EoZnlWvTxEj3AS1UpFTSLfqJEZZFfO9DDf9V1Ttf+B7sOG3qXPk0F3TZvR8kodgiH9XK/Nf6AjioQ0O5B7WsS9by4lgSP8Xe/TcGm+I4TLLICuvS8FVMir7FF/MLIg9GX5gOcS3eW0qiAKDJ55K+sJTLuWV6naOKNk4ZuRsxyq1E0zc5aRw9CwhWg021KuJuHm5is1deL3LCbSodLDanNF7BRDAmQTlpSTRSHSBa0AN3RUCRq30MqiH28DX4bD3ejeDJ+d1lerrDYrSiHswDgDJI0pXPybv8IcRnYjRYGyeBzYlcPkwyWFW0NKnZvE57LqKAQZihN/kTEzu5AFOH6MPd4OLE/ZLXJ0IIJJQPkVmb/6LofNDz1eRvYDxIhXKvVUh7uhztlnZv7L9SBZmUUSrPlW91Qi2ureArFr2B8mbqgKQgeXm8rYoXRLTNnAWKPttFMzMdNq6e0M8CNMAlhI9IF6NtqVME+GvTi4xIQWT/obrB24+VKR6qY5mpbEm6IvvsoJla/6mJCFtwsNwv+ZXxHlG7M3OqAOg=
